# Generated by Django 3.2.4 on 2021-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210605_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date and Time'),
        ),
    ]
