# Generated by Django 3.2.4 on 2021-06-12 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('appointment_for', models.CharField(blank=True, max_length=500)),
                ('appointment_dt', models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date and Time')),
                ('appointment_end_time', models.TimeField(blank=True, null=True)),
                ('appointment_state', models.CharField(choices=[('RE', 'Requested'), ('AC', 'Accepted'), ('DE', 'Declined')], default='RE', max_length=10)),
                ('short_note', models.CharField(blank=True, max_length=500)),
                ('appointment_status', models.CharField(choices=[('DU', 'Due'), ('TK', 'Taken')], default='DU', max_length=5)),
                ('booking_channel', models.CharField(choices=[('OP', 'App'), ('OC', 'Call')], default='OP', max_length=5)),
                ('appointment_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('doctor_dec_reason', models.CharField(blank=True, max_length=450, verbose_name="Doctor's Reason for Declining Appointment")),
                ('booked', models.BooleanField(default=False)),
                ('booked_doctor_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospitals.doctoroffice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('prep_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospitals.nurse')),
            ],
            options={
                'ordering': ['-appointment_dt'],
            },
        ),
    ]
