# Generated by Django 3.2.4 on 2021-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='practicing_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
