# Generated by Django 3.2.4 on 2021-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=80, upload_to='', verbose_name='Profile Picture', width_field=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=80, upload_to='', verbose_name='Profile Picture', width_field=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
