# Generated by Django 3.2.4 on 2021-07-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210702_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='uploads/imgs/dps/', verbose_name='Profile Picture'),
        ),
    ]
