# Generated by Django 3.2.4 on 2021-06-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, help_text='YYY-MMM-DDD', null=True, verbose_name='Date Of Birth')),
                ('identifier', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('profile_type', models.CharField(choices=[('PT', 'Patient'), ('DR', 'Doctor')], max_length=10, verbose_name='Register as')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('RNS', 'Rather Not Say')], default='M', max_length=7)),
                ('user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
